POST http://127.0.0.1:8000/agent/get_response
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYXphdmFsYWdhZkBnbWFpbC5jb20iLCJleHAiOjE3NjM5NDc4NDh9.2OEMvBx_8_mXOssBCB-QpyoUPWg7xyNmL7qw799q8zw
Content-Type: application/json

{
    "user_query": "Hola tengo examen el día viernes 28 de este mes sobre algoritmos voraces, necesito que me planifiques eventos de estudio para llegar preparado (detalla cada sesion)"
}

###

POST http://127.0.0.1:8000/agent/get_response
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYXphdmFsYWdhZkBnbWFpbC5jb20iLCJleHAiOjE3NjM5NDc4NDh9.2OEMvBx_8_mXOssBCB-QpyoUPWg7xyNmL7qw799q8zw
Content-Type: application/json

{
    "user_query": "Hola, quién eres?"
}