### 1. Create event by calendar -> for auth user in JWT
POST http://127.0.0.1:8000/events/create_event
Authorization: Bearer your_jwt_token_here
Content-Type: application/json

{
    "title": "Development Team Daily",
    "description": "Avance de tools del proyecto",
    "location": "Teams Meeting",
    "calendar_id": 11
}

### 2. Get all events by calendar -> for auth user in JWT
GET http://127.0.0.1:8000/events/get_all_events/11
Authorization: Bearer your_jwt_token_here

### 3. Get specific event by calendar -> for auth user in JWT
GET http://127.0.0.1:8000/events/get_event/17
Authorization: Bearer your_jwt_token_here

### 4. Update specific event -> for auth user in JWT
PUT http://127.0.0.1:8000/events/update_event/16
Authorization: Bearer your_jwt_token_here
Content-Type: application/json

{
    "title": "Clase Software 2",
    "description": "Curso 8vo ciclo",
    "location": "O2-402",
    "calendar_id": 10
}

### 5. Delete specific event -> for auth user in JWT
DELETE http://127.0.0.1:8000/events/delete_event/14
Authorization: Bearer your_jwt_token_here

### 6. Get event and its times event by event -> for auth user in JWT
GET http://127.0.0.1:8000/events/get_event_times/17
Authorization: Bearer your_jwt_token_here